// services/captionService.ts
// OpenSubtitles REST API integration for automatic subtitle fetching

import { useCallback } from "react";
import { useAppSettings } from "@/contexts/AppSettingsContext";

export interface SubtitleTrack {
  language: string;
  languageCode: string;
  url: string;
  format: "srt" | "vtt";
  isAutoGenerated: boolean;
  provider: "opensubtitles" | "embed" | "manual";
}

export interface AudioTrack {
  language: string;
  languageCode: string;
  label: string;
  url: string;
  isDubbed: boolean;
  provider: "embed" | "manual";
}

export interface MediaMetadata {
  tmdbId: string;
  title: string;
  year?: number;
  season?: number;
  episode?: number;
  mediaType: "movie" | "tv";
  originalLanguage: string;
}

// OpenSubtitles API configuration
const OPENSUBTITLES_BASE_URL = "https://rest.opensubtitles.org";
const OPENSUBTITLES_USER_AGENT = "FreeStream/1.0";

/**
 * Search for subtitles on OpenSubtitles
 */
export async function searchSubtitles(
  metadata: MediaMetadata
): Promise<SubtitleTrack[]> {
  try {
    const params = new URLSearchParams({
      query: metadata.title,
      ...(metadata.year && { year: metadata.year.toString() }),
      ...(metadata.mediaType === "tv" &&
        metadata.season && { season: metadata.season.toString() }),
      ...(metadata.mediaType === "tv" &&
        metadata.episode && { episode: metadata.episode.toString() }),
      languages: "en", // Prioritize English
      limit: "10",
    });

    const response = await fetch(
      `${OPENSUBTITLES_BASE_URL}/search/${metadata.tmdbId}?${params}`,
      {
        headers: {
          "User-Agent": OPENSUBTITLES_USER_AGENT,
          Accept: "application/json",
        },
      }
    );

    if (!response.ok) {
      console.warn(
        "[captionService] OpenSubtitles search failed:",
        response.status
      );
      return [];
    }

    const data = await response.json();

    // Transform OpenSubtitles response to our SubtitleTrack format
    return (data.data || [])
      .map((item: any) => ({
        language: item.attributes.language || "English",
        languageCode: item.attributes.language_code || "en",
        url: item.attributes.url || item.attributes.files?.[0]?.url || "",
        format: item.attributes.files?.[0]?.file_name?.endsWith(".vtt")
          ? "vtt"
          : "srt",
        isAutoGenerated: item.attributes.ai_generated || false,
        provider: "opensubtitles",
      }))
      .filter((track: SubtitleTrack) => track.url);
  } catch (error) {
    console.warn("[captionService] Failed to search subtitles:", error);
    return [];
  }
}

/**
 * Fetch subtitle content from URL
 */
export async function fetchSubtitleContent(
  url: string
): Promise<string | null> {
  try {
    const response = await fetch(url, {
      headers: {
        "User-Agent": OPENSUBTITLES_USER_AGENT,
      },
    });

    if (!response.ok) return null;

    const content = await response.text();
    return content;
  } catch {
    return null;
  }
}

/**
 * Convert SRT to VTT format for web video
 */
export function srtToVtt(srtContent: string): string {
  let vtt = "WEBVTT\n\n";

  const blocks = srtContent.trim().split(/\n\s*\n/);

  for (const block of blocks) {
    const lines = block.trim().split("\n");
    if (lines.length < 3) continue;

    // Skip the index line (first line)
    const timeLine = lines[1];
    const textLines = lines.slice(2);

    // Convert time format: 00:00:20,000 --> 00:00:24,400
    // to VTT format: 00:00:20.000 --> 00:00:24.400
    const vttTimeLine = timeLine.replace(/,/g, ".");

    vtt += `${vttTimeLine}\n${textLines.join("\n")}\n\n`;
  }

  return vtt;
}

/**
 * Create a blob URL for subtitle content
 */
export function createSubtitleBlobUrl(
  content: string,
  format: "srt" | "vtt"
): string {
  const mimeType = format === "vtt" ? "text/vtt" : "text/plain";
  const blob = new Blob([content], { type: mimeType });
  return URL.createObjectURL(blob);
}

/**
 * Get dubbed audio URL from embed provider (if available)
 * Checks for ?dub=english or similar parameters
 */
export function getDubbedAudioUrl(
  baseUrl: string,
  preferredLanguage: string = "en"
): string {
  try {
    const url = new URL(baseUrl);

    // Check if provider supports dub parameter
    const hostname = url.hostname.toLowerCase();

    if (
      hostname.includes("vidsrc") ||
      hostname.includes("embed.su") ||
      hostname.includes("autoembed")
    ) {
      url.searchParams.set("dub", preferredLanguage);
    }

    return url.toString();
  } catch {
    return baseUrl;
  }
}

/**
 * Auto-select best audio and subtitle tracks based on user preferences
 */
export function useCaptionService() {
  const { settings } = useAppSettings();

  const getRecommendedTracks = useCallback(
    async (metadata: MediaMetadata, embedUrl: string) => {
      const { preferredLanguage, autoSelectAudioSubtitles } = settings;

      const tracks = {
        audio: [] as AudioTrack[],
        subtitles: [] as SubtitleTrack[],
      };

      // 1. Check for English dubbed audio from embed provider
      if (
        autoSelectAudioSubtitles &&
        metadata.originalLanguage !== preferredLanguage.split("-")[0]
      ) {
        const dubbedUrl = getDubbedAudioUrl(
          embedUrl,
          preferredLanguage.split("-")[0]
        );
        if (dubbedUrl !== embedUrl) {
          tracks.audio.push({
            language: "English",
            languageCode: "en",
            label: "English (Dubbed)",
            url: dubbedUrl,
            isDubbed: true,
            provider: "embed",
          });
        }
      }

      // 2. Add native audio track
      tracks.audio.push({
        language: metadata.originalLanguage,
        languageCode: metadata.originalLanguage,
        label: metadata.originalLanguage.toUpperCase(),
        url: embedUrl,
        isDubbed: false,
        provider: "embed",
      });

      // 3. Fetch subtitles from OpenSubtitles if auto-select is enabled
      if (autoSelectAudioSubtitles) {
        const subtitles = await searchSubtitles(metadata);
        tracks.subtitles.push(...subtitles);
      }

      // 4. Always add "Off" option for subtitles
      tracks.subtitles.unshift({
        language: "Off",
        languageCode: "off",
        url: "",
        format: "vtt",
        isAutoGenerated: false,
        provider: "manual",
      });

      return tracks;
    },
    [settings]
  );

  return {
    getRecommendedTracks,
    searchSubtitles,
    fetchSubtitleContent,
    srtToVtt,
    createSubtitleBlobUrl,
  };
}

/**
 * Language code mapping for common languages
 */
export const LANGUAGE_CODE_MAP: Record<
  string,
  { code: string; label: string }
> = {
  en: { code: "en", label: "English" },
  es: { code: "es", label: "Spanish" },
  fr: { code: "fr", label: "French" },
  de: { code: "de", label: "German" },
  it: { code: "it", label: "Italian" },
  pt: { code: "pt", label: "Portuguese" },
  ja: { code: "ja", label: "Japanese" },
  ko: { code: "ko", label: "Korean" },
  zh: { code: "zh", label: "Chinese" },
  hi: { code: "hi", label: "Hindi" },
  ar: { code: "ar", label: "Arabic" },
  ru: { code: "ru", label: "Russian" },
  tr: { code: "tr", label: "Turkish" },
  pl: { code: "pl", label: "Polish" },
  nl: { code: "nl", label: "Dutch" },
  sv: { code: "sv", label: "Swedish" },
  da: { code: "da", label: "Danish" },
  no: { code: "no", label: "Norwegian" },
  fi: { code: "fi", label: "Finnish" },
  cs: { code: "cs", label: "Czech" },
  hu: { code: "hu", label: "Hungarian" },
  ro: { code: "ro", label: "Romanian" },
  th: { code: "th", label: "Thai" },
  vi: { code: "vi", label: "Vietnamese" },
  id: { code: "id", label: "Indonesian" },
  ms: { code: "ms", label: "Malay" },
  he: { code: "he", label: "Hebrew" },
  uk: { code: "uk", label: "Ukrainian" },
  el: { code: "el", label: "Greek" },
  hr: { code: "hr", label: "Croatian" },
  sk: { code: "sk", label: "Slovak" },
  sl: { code: "sl", label: "Slovenian" },
  bg: { code: "bg", label: "Bulgarian" },
  lt: { code: "lt", label: "Lithuanian" },
  lv: { code: "lv", label: "Latvian" },
  et: { code: "et", label: "Estonian" },
  sr: { code: "sr", label: "Serbian" },
  mk: { code: "mk", label: "Macedonian" },
  sq: { code: "sq", label: "Albanian" },
  mt: { code: "mt", label: "Maltese" },
  ga: { code: "ga", label: "Irish" },
  cy: { code: "cy", label: "Welsh" },
  eu: { code: "eu", label: "Basque" },
  ca: { code: "ca", label: "Catalan" },
  gl: { code: "gl", label: "Galician" },
  is: { code: "is", label: "Icelandic" },
  fa: { code: "fa", label: "Persian" },
  ur: { code: "ur", label: "Urdu" },
  bn: { code: "bn", label: "Bengali" },
  ta: { code: "ta", label: "Tamil" },
  te: { code: "te", label: "Telugu" },
  ml: { code: "ml", label: "Malayalam" },
  kn: { code: "kn", label: "Kannada" },
  gu: { code: "gu", label: "Gujarati" },
  pa: { code: "pa", label: "Punjabi" },
  mr: { code: "mr", label: "Marathi" },
  or: { code: "or", label: "Odia" },
  as: { code: "as", label: "Assamese" },
  ne: { code: "ne", label: "Nepali" },
  si: { code: "si", label: "Sinhala" },
  my: { code: "my", label: "Burmese" },
  km: { code: "km", label: "Khmer" },
  lo: { code: "lo", label: "Lao" },
  ka: { code: "ka", label: "Georgian" },
  am: { code: "am", label: "Amharic" },
  sw: { code: "sw", label: "Swahili" },
  zu: { code: "zu", label: "Zulu" },
  af: { code: "af", label: "Afrikaans" },
  xh: { code: "xh", label: "Xhosa" },
  yo: { code: "yo", label: "Yoruba" },
  ig: { code: "ig", label: "Igbo" },
  ha: { code: "ha", label: "Hausa" },
  so: { code: "so", label: "Somali" },
  ti: { code: "ti", label: "Tigrinya" },
};
